### ISSUE TITLE
The results that are submitted in the paper? is it class _accuracy or ss_accuracy? 

### ISSUE THREAD

**Issue by Tariq195** [winycg/HSAKD#6]
You have submitted the 80.7 for wrn-40-2 (Teacher Model), is it class_accuracy or ss_accuracy? I got this accuracy but as a class_accuracy, but you referreing best accuracy to the ss_accuracy that is  confusing me.

**Comment by winycg** [comment]
Thanks for your attention! Your understanding is correct. 80.7 is top-1 class_accuracy over 100 classes, which we report in our paper.  ss_accuracy is just a reference to the performance of the self-supervised augmented task. Our final target is to improve the class_accuracy.

By the way, we refer to the best accuracy as the ss_accuracy, because we think the best ss_accuracy may encode more meaningful auxiliary self-supervised augmented knowledge in the teacher.

**Comment by Tariq195** [comment]
Thank you for such a helpful reply. Again, you have done great work. I have read it thoroughly, and it is helping out me with the concepts that I need to build for distillation.
